cmake_minimum_required(VERSION 2.8)
set(esoinncpp_INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include/esoinncpp)

if (BUILD_SHARED_LIBS)
	if (MSVC)
	set(LIB_POSTFIX ".lib")
	elseif(APPLE)
	set(LIB_POSTFIX ".dylib")
	else()
	set(LIB_POSTFIX ".so")
	endif()
else()
	find_package(OpenMP)
	if (OPENMP_FOUND)
			set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
			set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
	endif()
	if (MSVC)
		set(LIB_POSTFIX ".lib")
		else()
	set(LIB_POSTFIX ".a")
	endif()
endif (BUILD_SHARED_LIBS)

if (MSVC)
set(esoinncpp_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/esoinncpp${LIB_POSTFIX} )
else()
set(esoinncpp_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/libesoinncpp${LIB_POSTFIX} )
endif()
